version: "3.8"

services:
  gateways:
    build: .
    networks:
      - conch_default
    labels:
      - traefik.http.routers.authors.rule=Host("conch.localhost") && PathPrefix(`/api/`)
      - traefik.http.middlewares.authors-no-prefix-mw.stripprefix.prefixes=/api/
      - traefik.http.routers.authors.middlewares=authors-no-prefix-mw@docker

networks:
  conch_default:
    external: true
